### ISSUE TITLE
latest draft/spec for module loading?

### ISSUE THREAD

**Issue by ryanflorence** [unpkg/babel-plugin-unpkg-rewrite#3]
I'm way behind these days, haven't messed w/ modules or followed any of it since I got a hold of webpack.

In AMD and SystemJS you could specify a `baseUrl` for any bare modules, is that something the target environments for this plugin don't have? Seems like this shouldn't even have to exist (thought I'm excited it does, exciting stuff!)

https://github.com/tc39/proposal-dynamic-import

**Comment by matthewp** [comment]
SystemJS was based on an older spec that never got finished. Some of the ideas are still alive and might be implemented in the future but I wouldn't hold your breath. What we have is `<script type="module">` which doesn't have a way to configure.

From [the spec](https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier) bare specifiers are forbidden. This is so that in the future some type of configuration might be added.

This plugin is a way to work around the fact that browsers won't have bare specifiers.

**Comment by ryanflorence** [comment]
Thanks!
